import Footer from "./components/Footer";
import "./globals.css";

export const metadata = {
  title: "NorvellFootball",
  description: "Generated by create next app",
};


export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <head>
        <link rel="preconnect" href="https://fonts.googleapis.com" />
        <link rel="preconnect" href="https://fonts.gstatic.com" />
        <link
          href="https://fonts.googleapis.com/css2?family=Raleway:ital,wght@0,100..900;1,100..900&family=Shadows+Into+Light&display=swap"
          rel="stylesheet"
        />
      </head>
      <body>
        {children}
        <Footer/>
        </body>
    </html>
  );
}

{/* <motion.div
className=" h-[90%] w-[35%] flex justify-center place-items-center rounded-[50px]  "
>
<Link href="/" className=" bg-[#eef1f2] border-2 border-black   w-[100%] flex  rounded-[100px] h-[100%] place-items-center " >
  <BiHomeSmile className="text-[1.6rem] text-blue-900  " />
  <p className="ml-[.3rem] font-semibold ">Home</p>
</Link>
</motion.div> */}

